- name: Install pi5 - Hailo AI HAT+
  hosts: pi5
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - wget
          - unzip
          - git
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Install testing tools
      apt:
        name:
          - stress

    - name: Hailo software
      apt:
        name:
          - hailo-all      
          - rpicam-apps
